### ISSUE TITLE
How to export predicted result in aneurysm3D example

### ISSUE THREAD

**Issue by syusaku625** [rezaakb/pinns-torch#2]

**Comment by rezaakb** [comment]
If you use our package directly, you can access predictions as described in the tutorial. However, you raise a good point, and we will add it to the package for use with the Hydra config file.

`preds_list = trainer.predict(model=model, datamodule=datamodule)`
`preds_dict = pinnstorch.utils.fix_predictions(preds_list)`

**Comment by syusaku625** [comment]
I tried to export predicted data following your advice, but I got a error.
Please give me advise how solve this error.

Traceback (most recent call last):
  File "/home/shusaku/pinns-torch/pinnstorch/utils/utils.py", line 73, in wrap
    metric_dict, object_dict = task_func(
  File "/home/shusaku/pinns-torch/pinnstorch/train.py", line 175, in train
    preds_list = trainer.predict(
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
    return self.predict_loop.run()
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/loops/prediction_loop.py", line 122, in run
    self._predict_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/loops/prediction_loop.py", line 263, in _predict_step
    call._call_callback_hooks(trainer, "on_predict_batch_end", predictions, *hook_kwargs.values())
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/shusaku/pinns-torch/test/lib/python3.10/site-packages/lightning/pytorch/callbacks/progress/rich_progress.py", line 576, in on_predict_batch_end
    assert self.predict_progress_bar_id is not None
AssertionError

**Comment by rezaakb** [comment]
Sorry for any inconvenience. We have added a new feature to the package. Now you can add `save_pred: true` to the config file, and the prediction will be saved in the output directory. Please let me know if you still have issues with saving predictions.
