### ISSUE TITLE
Project root directory not found

### ISSUE THREAD

**Issue by SteJSch** [rezaakb/pinns-torch#4]
I installed your packages as described and tried to run 

python examples/navier_stokes/train.py

but i get an error;

`
Traceback (most recent call last):
  File "[..]pinns-torch/examples/navier_stokes/train.py", line 8, in <module>
    import pinnstorch
  File [..]local/lib/python3.10/site-packages/pinnstorch/__init__.py", line 1, in <module>
    from pinnstorch.train import train
  File "[..].local/lib/python3.10/site-packages/pinnstorch/train.py", line 15, in <module>
    rootutils.setup_root(__file__, indicator=".project-root", pythonpath=True)
  File "[..].local/lib/python3.10/site-packages/rootutils/rootutils.py", line 148, in setup_root
    path = find_root(search_from, indicator)
  File "[..].local/lib/python3.10/site-packages/rootutils/rootutils.py", line 70, in find_root
    raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
FileNotFoundError: Project root directory not found. Indicators: ['.project-root']

`
Hope you can help...

**Comment by rezaakb** [comment]
Thank you for reporting the bug. We have made changes to the package to fix this bug. Please reinstall it and let us know if you encounter any issues.
